Remove ical4android dependency and Tasks/Jtx/CalDAV/Webcal/WebDAV related code and resources
The ical4android library uses the

 android.permission.READ_CALENDAR
 android.permission.WRITE_CALENDAR

permissions. We don't need those and also don't want those permissions
to show up, so we need to remove the submodule.

Update ProGuard rules to fix
ERROR: R8: Missing class org.slf4j.impl.StaticLoggerBinder (referenced from: void org.slf4j.LoggerFactory.bind() and 3 other contexts)